name: Red Rock Silver
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0b0d'
    - '#cc2720'
    - '#d9d9d9'
    - '#404142'
    - '#6c6d6e'
  brandStrength: 0.7641943397466093
  lightness: 0.16918890527449548
  saturation: 1
  rhythmicContrast: 0.8737544158939272
purpose: []
